In [6]:
import pandas as pd
import numpy as np

In [8]:
raw = pd.read_excel('SDC.xlsx', sheet_name='Hoja1', header=None)
raw.head(15)

,0,1,2,3,4,5,6,7,8,9,...,27,28,29,30,31,32,33,34,35,36
0,Ventas,NaN,12,7,8,13,6,21,17,17,...,38,30,41,41,35,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,NaN,NaN
3,Generadas,5,6,11,23,26,43,55,36,56,...,85,74,95,82,32,519,1178,450,1697.0,0.392457
4,Aprobadas,1,2,7,14,8,13,30,19,26,...,41,42,44,35,12,215,451,201,666.0,0.509009
5,Condicionadas,0,0,1,0,4,0,3,0,1,...,14,16,17,10,9,100,287,102,387.0,NaN
6,Rechazadas,4,4,4,9,14,22,17,13,13,...,30,16,30,33,9,163,392,137,555.0,NaN
7,Formalizadas,1,1,5,11,3,6,17,9,7,...,18,16,19,13,4,105,234,91,339.0,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,% de Aprobación,0.2,0.333333,0.636364,0.608696,0.307692,0.302326,0.545455,0.527778,0.464286,...,0.482353,0.567568,0.463158,0.426829,0.375,0.414258,0.382852,0.446667,NaN,NaN
10,% de Formalizacion,1,0.5,0.714286,0.785714,0.375,0.461538,0.566667,0.473684,0.269231,...,0.439024,0.380952,0.431818,0.371429,0.333333,0.488372,0.518847,0.452736,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,N.º de solicitudes ingresadas por financiera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Financiera,0,0,0,0,0,0,0,0,51,...,85,74,95,82,32,TOTAL,% PARTICIPACION,NaN,NaN,NaN

DATASET 1: Indicadores Mensuales SDC

In [ ]:
header1 = raw.iloc[2, 0:37].tolist()
header1[35] = 'Total General'
header1[36] = 'Proporcion General'

data1 = raw.iloc[[3,4,5,6,7,9,10], 0:37].copy()
data1.columns = header1
data1 = data1.reset_index(drop=True)
data1

In [ ]:
valores_nulos = data1.isnull().sum()
valores_nulos[valores_nulos > 0]

In [ ]:
data1['Total General'] = data1['Total General'].fillna(data1['Total General'].median())

In [ ]:
data1['Proporcion General'] = data1['Proporcion General'].fillna(round(data1['Proporcion General'].mean(), 4))

In [ ]:
valores_nulos = data1.isnull().sum().sum()
valores_nulos

In [ ]:
data1.to_csv('Indicadores_Mensuales_SDC.csv', index=False)

DATASET 2: Solicitudes por Financiera

In [9]:
header2 = raw.iloc[2, 0:34].tolist()
header2[0] = 'Financiera'

data2 = raw.iloc[16:30, 0:34].copy()
data2.columns = header2
data2 = data2.reset_index(drop=True)
data2

,Financiera,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Diciembre, 25","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025
0,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.000518
1,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121,0.062727
2,Banorte,-,-,-,-,-,-,-,-,1,...,69,53,33,33,33,34,15,10,790,0.409539
3,BBVA,-,-,-,-,-,-,-,-,12,...,6,7,10,12,7,11,16,3,202,0.104717
4,Ensueño,-,-,-,-,-,-,-,-,-,...,22,9,4,3,1,8,8,7,144,0.07465
5,FinanMadrid,-,-,-,-,-,-,-,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,0.001037
6,INBURSA,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
7,MSTART,-,-,-,-,-,-,-,-,-,...,3,12,12,9,5,11,6,1,156,0.080871
8,Nexu,-,-,-,-,-,-,-,-,19,...,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,135,0.069984
9,Santander,-,-,-,-,-,-,-,-,1,...,11,26,18,25,21,18,30,7,442,0.229134
10,Scotiabank,-,-,-,-,-,-,-,-,-,...,NaN,3,2,1,3,9,6,4,41,0.021255
11,Sumafin,-,-,-,-,-,-,-,-,-,...,-,2,4,1,NaN,NaN,NaN,NaN,7,0.003629
12,Bajio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,0.000518
13,Kuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4,4,1,NaN,9,0.004666

In [10]:
print('Cantidad de guiones (cero explicito):', (data2 == '-').sum().sum())
print('Cantidad de NaN reales:', data2.isnull().sum().sum())

Cantidad de guiones (cero explicito): 171
Cantidad de NaN reales: 121

In [11]:
data2 = data2.replace('-', 0)

In [12]:
columnas_mes = [c for c in data2.columns if c != 'Financiera']
for columna in columnas_mes:
    data2[columna] = data2[columna].fillna(0)

In [13]:
valores_nulos = data2.isnull().sum().sum()
valores_nulos

np.int64(0)

In [14]:
data2.to_csv('Solicitudes_por_Financiera_SDC.csv', index=False)

DATASET 3: Motivos de SDC No Autorizadas

In [15]:
header3 = raw.iloc[32, 0:12].tolist()
header3[0] = 'Motivo'

data3 = raw.iloc[33:37, 0:12].copy()
data3.columns = header3
data3 = data3.reset_index(drop=True)
data3

,Motivo,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24"
0,Mal Buro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Score bajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Capacidad de pago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
valores_nulos = data3.isnull().sum().sum()
valores_nulos

np.int64(44)

In [17]:
columnas_mes3 = [c for c in data3.columns if c != 'Motivo']
for columna in columnas_mes3:
    data3[columna] = data3[columna].fillna(0)

In [18]:
valores_nulos = data3.isnull().sum().sum()
valores_nulos

np.int64(0)

In [19]:
data3.to_csv('Motivos_No_Autorizadas_SDC.csv', index=False)

DATASET 4: Motivos de SDC No Formalizadas

In [20]:
header4 = raw.iloc[40, 0:12].tolist()
header4[0] = 'Motivo'

data4 = raw.iloc[41:45, 0:12].copy()
data4.columns = header4
data4 = data4.reset_index(drop=True)
data4

,Motivo,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24","Octubre, 24","Noviembre, 24"
0,Compra en otro lado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Falta importe para enganche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Espera comprar en futuro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
valores_nulos = data4.isnull().sum().sum()
valores_nulos

np.int64(44)

In [22]:
columnas_mes4 = [c for c in data4.columns if c != 'Motivo']
for columna in columnas_mes4:
    data4[columna] = data4[columna].fillna(0)

In [23]:
valores_nulos = data4.isnull().sum().sum()
valores_nulos

np.int64(0)

In [24]:
data4.to_csv('Motivos_No_Formalizadas_SDC.csv', index=False)

In [26]:
print('Dataset 2 - Solicitudes por Financiera:', data2.isnull().sum().sum(), 'nulos')
print('Dataset 3 - Motivos No Autorizadas:', data3.isnull().sum().sum(), 'nulos')
print('Dataset 4 - Motivos No Formalizadas:', data4.isnull().sum().sum(), 'nulos')

Dataset 2 - Solicitudes por Financiera: 0 nulos
Dataset 3 - Motivos No Autorizadas: 0 nulos
Dataset 4 - Motivos No Formalizadas: 0 nulos