In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv('Citas_Digital_Filtrado.csv')
data.head(5)

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [4]:
data1= pd.read_csv('Citas_Digital_Filtrado.csv', skiprows=1)
data1

,Saul,Unnamed: 1,Guillermo,Unnamed: 3,Finalizado,0.9,1.0,0.0,0.0.1,Nancy,"Ya visito la Agencia el dia jueves 17, interesado en GN8 PHEV","Pide arrendamiento, unicamente se esta en espera de contacto con el contador, posibilidad de compra 90%","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia mas de 3hrs","No, se espero a que visitara la agencia para ser asignado",Comenta que no se le hizo atractivo el arrendamiento
0,Saul,NaN,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
1,Saul,NaN,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
2,Saul,NaN,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
3,Saul,NaN,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
4,Saul,NaN,Antonio,NaN,Activo,0.85,1.0,1.0,0.0,Mauricio,Visito la agencia el dia 13 de abril,Si hubo solicitud de credito,Si realizo prueba de manejo,"Lo resivio por parte del asesor, ya que el dia...",Se asigno hasta que visitara Piso,Solo estamos en espera de venta de auto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,Ana,2026-07-22,Maira Escalante,NaN,Activo,0.8,1.0,1.0,0.0,Pedro Antonio,NaN,NaN,NaN,NaN,NaN,NaN
671,Ignacio,2026-07-22,Zaira Macip,NaN,Activo,0.5,0.0,0.0,0.0,Aurelio,NaN,NaN,NaN,NaN,NaN,NaN
672,Ignacio,2026-07-27,Julio Hernandez,NaN,Activo,0.5,1.0,0.0,0.0,Victor,NaN,NaN,NaN,NaN,NaN,NaN
673,Ignacio,2026-07-24,Xhunaxhi Vicente,NaN,Activo,1,1.0,1.0,1.0,Ignacio,NaN,NaN,NaN,NaN,NaN,NaN
674,Ignacio,2026-07-29,DR Jairo Rodriguez Farias,NaN,Activo,1,1.0,1.0,1.0,Victor,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
valores_nulos=data1.isnull().sum()
valores_nulos

Saul                                                                                                        16
Unnamed: 1                                                                                                 600
Guillermo                                                                                                   21
Unnamed: 3                                                                                                 673
Finalizado                                                                                                  35
0.9                                                                                                         74
1.0                                                                                                          1
0.0                                                                                                          2
0.0.1                                                                                                        5
Nancy                                                                                                       32
Ya visito la Agencia  el dia jueves 17, interesado en GN8 PHEV                                             183
Pide arrendamiento, unicamente se esta en espera de contacto con el contador, posibilidad de compra 90%    297
Si, hizo prueba de manejo                                                                                  321
Si recibio procesos wow, estuvo en la agencia mas de 3hrs                                                  312
No, se espero a que visitara la agencia para ser asignado                                                  323
Comenta que no se le hizo atractivo el arrendamiento                                                       660
dtype: int64

In [8]:
valores_nulos = data.isnull().sum().sum()
valores_nulos

np.int64(3557)

In [10]:
data2 = data.drop(['Telefono '], axis=1)
data2.head(5)

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaN,Guillermo,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaN,Roberto,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaN,Irving,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaN,Oswaldo,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaN,Rodrigo,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...

In [11]:
data3 = data2.copy()

In [13]:
data3['BDC '] = data3['BDC '].ffill()

In [14]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                       601
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [15]:
data3['Fecha'] = data3['Fecha'].fillna('Sin fecha registrada')

In [16]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                               21
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [18]:
data3['Nombre Cliente '] = data3['Nombre Cliente '].fillna('Sin nombre registrado ')

In [19]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                              35
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [20]:
data3['Estatus de Lead'] = data3['Estatus de Lead'].bfill()

In [21]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                          74
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [22]:
data3['Potencial de compra'] = pd.to_numeric(data3['Potencial de compra'], errors='coerce')
data3['Potencial de compra'].isnull().sum()

np.int64(79)

In [23]:
data3['Potencial de compra'] = data3['Potencial de compra'].fillna(round(data3['Potencial de compra'].mean(), 2))

In [24]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           1
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [25]:
data3['PDM'] = data3['PDM'].fillna(data3['PDM'].median())

In [26]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           2
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [27]:
data3['SDC'] = data3['SDC'].fillna(0)

In [28]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         5
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [29]:
data3['Venta'] = data3['Venta'].fillna(data3['Venta'].mode()[0])

In [30]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                              32
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [31]:
data3['Asesor Asignado'] = data3['Asesor Asignado'].ffill()

In [32]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?         183
¿Por que no hay solicitud de credito?       297
¿Por que no hubo prueba de manejo ?         321
¿Por que no hubo proceso wow?               312
¿Por que se asigno antes de vistar piso?    323
Unnamed: 15                                 660
dtype: int64

In [33]:
columnas_motivo = ['¿Por que no ha visitado la agencia?', '¿Por que no hay solicitud de credito?',
                    '¿Por que no hubo prueba de manejo ?', '¿Por que no hubo proceso wow?',
                    '¿Por que se asigno antes de vistar piso?']

for columna in columnas_motivo:
    data3[columna] = data3[columna].fillna('No aplica')

In [34]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                           0
Fecha                                         0
Nombre Cliente                                0
Estatus de Lead                               0
Potencial de compra                           0
PDM                                           0
SDC                                           0
Venta                                         0
Asesor Asignado                               0
¿Por que no ha visitado la agencia?           0
¿Por que no hay solicitud de credito?         0
¿Por que no hubo prueba de manejo ?           0
¿Por que no hubo proceso wow?                 0
¿Por que se asigno antes de vistar piso?      0
Unnamed: 15                                 660
dtype: int64

In [35]:
data3['Unnamed: 15'] = data3['Unnamed: 15'].fillna('Sin comentarios adicionales')

In [36]:
valores_nulos = data3.isnull().sum()
valores_nulos

BDC                                         0
Fecha                                       0
Nombre Cliente                              0
Estatus de Lead                             0
Potencial de compra                         0
PDM                                         0
SDC                                         0
Venta                                       0
Asesor Asignado                             0
¿Por que no ha visitado la agencia?         0
¿Por que no hay solicitud de credito?       0
¿Por que no hubo prueba de manejo ?         0
¿Por que no hubo proceso wow?               0
¿Por que se asigno antes de vistar piso?    0
Unnamed: 15                                 0
dtype: int64

In [37]:
valores_nulos = data3.isnull().sum().sum()
valores_nulos

np.int64(0)

In [38]:
data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 676 entries, 0 to 675
Data columns (total 15 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       676 non-null    str
 1   Fecha                                     676 non-null    str
 2   Nombre Cliente                            676 non-null    str
 3   Estatus de Lead                           676 non-null    str
 4   Potencial de compra                       676 non-null    float64
 5   PDM                                       676 non-null    float64
 6   SDC                                       676 non-null    float64
 7   Venta                                     676 non-null    float64
 8   Asesor Asignado                           676 non-null    str
 9   ¿Por que no ha visitado la agencia?       676 non-null    str
 10  ¿Por que no hay solicitud de credito?     676 non-null    str
 11  ¿Por que no hubo prueba de manejo ?       676 non-null    str
 12  ¿Por que no hubo proceso wow?             676 non-null    str
 13  ¿Por que se asigno antes de vistar piso?  676 non-null    str
 14  Unnamed: 15                               676 non-null    str
dtypes: float64(4), str(11)
memory usage: 79.3 KB

In [39]:
data3.to_csv('Citas_Digital_Sin_Nulos.csv', index=False)